---
title: Publications
---

# Peer-reviewed academic publications
<!-- references -->

## 2024

- Glassmann U., **Gräbner-Radkowitsch C.** (Eds.) (2024). _The Political Economy of Italy and the Center-Periphery Perspective on Europe_. Marburg: Metropolis. [Available online](https://www.metropolis-verlag.de/dl/OpenAccess/1560.pdf;jsessionid=1F0FC253342799BE437CBD7864490C47).

- **Gräbner-Radkowitsch C.**, Kapeller J. (2024). Development Models in the EU: Opportunities and Challenges, in: Glassmann U., **Gräbner-Radkowitsch C.** (Eds.): _The Political Economy of Italy and the Center-Periphery Perspective on Europe_. Marburg: Metropolis, pp. 49--79.

- Kapeller J., **Gräbner-Radkowitsch C.**, Hornykewycz A. (2024). Corporate power and global value chains: current approaches for conceptualizing the power of multinationals, _Review of Evolutionary Political Economy_. doi: [10.1007/s43253-024-00121-5](https://doi.org/10.1007/s43253-024-00121-5)

## 2023

- **Gräbner-Radkowitsch C.**, Strunk B. (2023). Degrowth and the Global South: The Twin Problem of Global Dependencies, _Ecological Economics_, **213**: 107946. doi: [10.1016/j.ecolecon.2023.107946](https://doi.org/10.1016/j.ecolecon.2023.107946)

- **Gräbner-Radkowitsch C.**, Hager T., Hornykewycz A. (2023). Competing for Sustainability? An Institutionalist Analysis of the New Development Model of the European Union, _Journal of Economic Issues_, **57**(2): 676--683. doi: [10.1080/00213624.2023.2203637](https://doi.org/10.1080/00213624.2023.2203637)

- **Gräbner-Radkowitsch C.**, Strunk B. (2023). Degrowth and the Global South? How Institutionalism Can Complement a Timely Discourse on Ecologically Sustainable Development in an Unequal World, _Journal of Economic Issues_, **57**(2): 476--483. doi: [10.1080/00213624.2023.2201640](https://doi.org/10.1080/00213624.2023.2201640)

## 2022

- **Gräbner-Radkowitsch C.** (2022). Elements of an Evolutionary Approach to Comparative Economic Studies: Complexity, Systemism, and Path Dependent Development, in: Dallago B., Casagrande S. (Eds.): _Routledge Handbook of Comparative Economic Systems_. London and New York: Routledge, pp. 81--102.

- **Gräbner-Radkowitsch C.**, Heimberger P., Kapeller J., Landesmann M., Schütz B. (2022). The Evolution of Debtor-Creditor Relationships within a Monetary Union: Trade Imbalances, Excess Reserves and Economic Policy, _Structural Change and Economic Dynamics_, **62**: 262--289. doi: [10.1016/j.strueco.2022.05.004](https://doi.org/10.1016/j.strueco.2022.05.004)

- **Gräbner-Radkowitsch C.**, Tamesberger D., Heimberger P., Kapelari T., Kapeller J. (2022). Trade Models in the European Union, _Economic Annals_, **67**(235): 7--36. doi: [10.2298/eka2235007g](https://doi.org/10.2298/eka2235007g)

- **Gräbner-Radkowitsch C.**, Hafele J. (2022). Why Fostering Socio-economic Convergence in the EU Is Necessary for Successful Climate Change Mitigation, in: Heinrich Böll Foundation, ZOE-Institute for Future-Fit Economies, Finanzwende Recherche (Eds.): _Making the Great Turnaround Work: Economic Policy for a Green and Just Transition_. Berlin: Heinrich Böll Foundation, pp. 104--114.

- **Gräbner C.**, Hornykewycz A. (2022). Capability Accumulation and Product Innovation: An Agent-Based Perspective, _Journal of Evolutionary Economics_, **32**(1): 87--121. doi: [10.1007/s00191-021-00732-9](https://doi.org/10.1007/s00191-021-00732-9)

## 2021

- Aistleitner M., **Gräbner C.**, Hornykewycz A. (2021). Theory and Empirics of Capability Accumulation: Implications for Macroeconomic Modelling, _Research Policy_, **50**(6): 104258. doi: [10.1016/j.respol.2021.104258](https://doi.org/10.1016/j.respol.2021.104258)

- Cordes C., Elsner W., Graebner C., Heinrich T., Henkel J., Schwardt H., Schwesinger G., Su T. (2021). The Collapse of Cooperation: The Endogeneity of Institutional Break-up and Its Asymmetry with Emergence, _Journal of Evolutionary Economics_, **31**(4): 1291--1315. doi: [10.1007/s00191-021-00739-2](https://doi.org/10.1007/s00191-021-00739-2)

- **Gräbner C.**, Heimberger P., Kapeller J., Springholz F. (2021). Understanding Economic Openness: A Review of Existing Measures, _Review of World Economics_, **157**(1): 87--120. doi: [10.1007/s10290-020-00391-1](https://doi.org/10.1007/s10290-020-00391-1)

- Kapeller J., **Gräbner C.** (2021). Konzernmacht in Globalen Güterketten, in: Fischer K., Reiner C., Staritz C. (Eds.): _Globale Warenketten Und Ungleiche Entwicklung. Arbeit, Kapital, Konsum, Natur_. Wien: mandelbaum verlag, pp. 195--213.

- Kapeller J., **Gräbner-Radkowitsch C.** (2021). Standortwettbewerb Und Deindustrialisierung: Das Beispiel MAN Als Lehrbuchfall, _WISO_, **44**(4): 33--52.

## 2020

- **Gräbner C.**, Heimberger P., Kapeller J., Schütz B. (2020). Is the Eurozone Disintegrating? Macroeconomic Divergence, Structural Polarisation, Trade and Fragility, _Cambridge Journal of Economics_, **44**(3): 647--669. doi: [10.1093/cje/bez059](https://doi.org/10.1093/cje/bez059)

- **Gräbner C.**, Heimberger P., Kapeller J. (2020). Pandemic Pushes Polarisation: The Corona Crisis and Macroeconomic Divergence in the Eurozone, _Journal of Industrial and Business Economics_, **47**(3): 425--438. doi: [10.1007/s40812-020-00163-w](https://doi.org/10.1007/s40812-020-00163-w)

- **Gräbner C.**, Strunk B. (2020). Pluralism in Economics: Its Critiques and Their Lessons, _Journal of Economic Methodology_, **27**(4): 311--329. doi: [10.1080/1350178x.2020.1824076](https://doi.org/10.1080/1350178x.2020.1824076)

- **Gräbner C.**, Heimberger P., Kapeller J., Schütz B. (2020). Structural Change in Times of Increasing Openness: Assessing Path Dependency in European Economic Integration, _Journal of Evolutionary Economics_, **30**(5): 1467--1495. doi: [10.1007/s00191-019-00639-6](https://doi.org/10.1007/s00191-019-00639-6)

- **Gräbner C.**, Elsner W., Lascaux A. (2020). Trust and Social Control: Sources of Cooperation, Performance, and Stability in Informal Value Transfer Systems, _Computational Economics_: 1--26. doi: [10.1007/s10614-020-09994-0](https://doi.org/10.1007/s10614-020-09994-0)

## 2019

- Flechtner S., **Gräbner C.** (2019). The Heterogeneous Relationship between Income and Inequality: A Panel Co-Integration Approach, _Economics Bulletin_, **39**(4): 2540--2549.

- **Gräbner C.**, Bale C., Furtado B., Pereira B., Gentile J., Henderson H., Lipari F. (2019). Getting the Best of Both Worlds? Developing Complementary Equation-Based and Agent-Based Models, _Computational Economics_, **53**(2): 763--782. doi: [10.1007/s10614-017-9763-8](https://doi.org/10.1007/s10614-017-9763-8)

- Heinrich T., **Gräbner C.** (2019). Beyond Equilibrium: Revisiting Two-Sided Markets from an Agent-Based Modelling Perspective, _International Journal of Computational Economics and Econometrics_, **9**(3): 153--180. doi: [10.1504/ijcee.2019.100558](https://doi.org/10.1504/ijcee.2019.100558)

- Kapeller J., **Gräbner C.**, Heimberger P. (2019). Economic Polarisation in Europe: Causes and Policy Options, _wiiw Research Report_, **440**.

- Kapeller J., **Gräbner C.**, Heimberger P. (2019). _Wirtschaftliche Polarisierung in Europa_. Berlin: Friedrich-Ebert-Stiftung. [Available online](https://www.fes.de/wirtschaftliche-polarisierung-in-europa).

## 2018

- **Gräbner C.**, Heinrich T., Kudic M., Vermeulen B. (2018). The Dynamics of and on Networks: An Introduction, _International Journal of Computational Economics and Econometrics_, **8**(3/4): 229--241.

- **Gräbner C.** (2018). Formal Approaches to Socio-economic Analysis---Past and Perspectives, _Forum for Social Economics_, **47**(1): 32--63. doi: [10.1080/07360932.2015.1042491](https://doi.org/10.1080/07360932.2015.1042491)

- **Gräbner C.** (2018). How to Relate Models to Reality? An Epistemological Framework for the Validation and Verification of Computational Models, _Journal of Artificial Societies and Simulation_, **21**(3). doi: [10.18564/jasss.3772](https://doi.org/10.18564/jasss.3772)

- **Gräbner C.**, Heimberger P., Kapeller J., Springholz F. (2018). Measuring Economic Openness: A Review of Existing Measurements and Empirical Practices, _ICAE Working Paper_, **84**.

- **Gräbner C.**, Elsner W., Lascaux A. (2018). To Trust or to Control: Informal Value Transfer Systems and Computational Analysis in Institutional Economics, _Journal of Economic Issues_, **52**(2): 559--569. doi: [10.1080/00213624.2018.1469936](https://doi.org/10.1080/00213624.2018.1469936)

## 2017

- **Gräbner C.** (2017). The Complementary Relationship Between Institutional and Complexity Economics: The Example of Deep Mechanismic Explanations, _Journal of Economic Issues_, **51**(2): 392--400. doi: [10.1080/00213624.2017.1320915](https://doi.org/10.1080/00213624.2017.1320915)

- **Gräbner C.** (2017). The Complexity of Economies and Pluralism in Economics, _Journal of Contextual Economics_, **137**(3): 193--225. doi: [10.3790/jce.137.3.193](https://doi.org/10.3790/jce.137.3.193)

- **Gräbner C.** (2017). Dealing Adequately with the Political Element in Formal Modelling, in: Hanappi H., Katsikides S., Scholz-Wäckerle M. (Eds.): _Theory and Method of Evolutionary Political Economy_. London: Routledge, pp. 236--254.

- **Gräbner C.**, Kapeller J. (2017). The Micro-Macro Link in Heterodox Economics, in: Jo T., Chester L., D'Ippolliti C. (Eds.): _The Handbook of Heterodox Economics_. London, UK, New York, NY: Routledge, pp. 145--159.

- **Gräbner C.**, Heinrich T. (2017). Von Onlineplattformen Und Mittelalterlichen Märkten, _TATuP Zeitschrift für Technikfolgenabschätzung in Theorie und Praxis_, **26**(3): 23--29. doi: [10.14512/tatup.26.3.23](https://doi.org/10.14512/tatup.26.3.23)

- **Gräbner C.** (2017). Die Rolle Des Gleichgewichtskonzepts in Der Mikroökonomischen Ausbildung, in: van Treeck T., Urban J. (Eds.): _Wirtschaft Neu Denken_. Berlin: iRights media, pp. 60--73.

## 2016

- **Gräbner C.** (2016). Agent-Based Computational Models-- a Formal Heuristic for Institutionalist Pattern Modelling?, _Journal of Institutional Economics_, **12**(1): 241--261. doi: [10.1017/s1744137415000193](https://doi.org/10.1017/s1744137415000193)

- **Gräbner C.**, Heinrich T., Schwardt H. (Eds.) (2016). _Policy Implications of Recent Advances in Evolutionary and Institutional Economics_. New York: Routledge.

- Pereira B., Henderson H., Lipari F., Furtado B., Bale C., Gentile J., **Gräbner C.** (2016). Errata in ``The Political Economy of the Kuznets Curve'', _Review of Development Economics_, **20**(4): 817--819. doi: [10.1111/rode.12285](https://doi.org/10.1111/rode.12285)

- Schwardt H., **Gräbner C.**, Heinrich T., Cordes C., Schwesinger G. (2016). Economic Complexity and Trade-Offs in Policy Decisions, in: **Gräbner C.**, Heinrich T., Schwardt H. (Eds.): _Policy Implications of Recent Advances in Evolutionary and Institutional Economics_. London and New York: Routledge, pp. 3--19.

## 2015

- **Gräbner C.**, Kapeller J. (2015). New Perspectives on Institutionalist Pattern Modeling: Systemism, Complexity, and Agent-Based Modeling, _Journal of Economic Issues_, **49**(2): 433--440. doi: [10.1080/00213624.2015.1042765](https://doi.org/10.1080/00213624.2015.1042765)

<!-- /references -->

# Non-peer-reviewed and non-academic publications

<!-- nonacademicpubs -->

## 2024

- **Gräbner-Radkowitsch C.**, Strunk B. (2024). Quelle Place Pour Le Sud Global Dans La D\'ecroissance?, in: _The Conversation_, July: [Link](https://theconversation.com/quelle-place-pour-le-sud-global-dans-la-decroissance-225209).

## 2023

- **Gräbner-Radkowitsch C.**, Strunk B. (2023). Degrowth and the Global South: Remarks on the Twin Problem of Structural Interdependencies, in: _Developing Economics_, June: [Link](https://developingeconomics.org/2023/11/06/degrowth-and-the-global-south-remarks-on-the-twin-problem-of-structural-interdependencies/).

- **Gräbner-Radkowitsch C.**, Strunk B. (2023). Degrowth Und Der Globale Süden, in: _Postwachstum Blog_, October: [Link](https://www.postwachstum.de/degrowth-und-der-globale-sueden-20231023).

## 2022

- **Gräbner-Radkowitsch C.**, Lage J., Wiese F. (2022). Zur Ökonomischen Bedeutung von Suffizienz, in: _Makronom -- Online Magazin für Wirtschaftspolitik_, June: [Link](https://makronom.de/zur-oekonomischen-bedeutung-von-suffizienz-42099).

## 2021

- Altreiter C., Rogojanu A., **Gräbner C.**, Pühringer S., Wolfmayr G. (2021). 20 Jahre Gute Absichten in Der Wissenschaftspolitik, in: _Die Presse_, August: [Link](https://www.diepresse.com/6024122/20-jahre-gute-absichten-in-der-wissenschaftspolitik).

- Altreiter C., Rogojanu A., **Gräbner C.**, Pühringer S., Wolfmayr G. (2021). Befristete Uni-Stellen: Drei Fehlschlüsse Mit Gravierenden Folgen, in: _Der Standard_, July: [Link](https://www.derstandard.at/story/2000128392310/befristete-uni-stellen-drei-fehlschluesse-mit-gravierenden-folgen).

- **Gräbner-Radkowitsch C.**, Strunk B. (2021). Pluralism in Economics -- Its Critiques and Their Lessons, in: _Developing Economics_, March: [Link](https://developingeconomics.org/2021/02/03/pluralism-in-economics-its-critiques-and-their-lessons/).

- **Gräbner-Radkowitsch C.**, Hafele J. (2021). What Are the Reasons for the Lack of Overall Convergence in the EU? A Structuralist View, in: _The Rebuilding Macroeconomics Blog_, August: [Link](https://www.rebuildingmacroeconomics.ac.uk/post/what-are-the-reasons-for-the-lack-of-overall-convergence-in-the-eu-a-structuralist-view).

- **Gräbner C.**, Heimberger P., Kapeller J., Schütz B. (2021). Ökonomische Offenheit: Die Vermessung Der Globalisierung, in: _Oekonomenstimme_, February: [Link](https://www.oekonomenstimme.org/artikel/2021/02/oekonomische-offenheit-die-vermessung-der-globalisierung/).

## 2020

- **Gräbner C.**, Strunk B. (2020). Kritik an Der Pluralen Ökonomik -- Was Ist Dran Und Warum Ist Das Wichtig?, in: _Oekonomenstimme_, November: [Link](https://www.oekonomenstimme.org/artikel/2020/11/kritik-an-der-pluralen-oekonomik--was-ist-dran-und-warum-ist-das-wichtig/).

- Heimberger P., **Gräbner C.**, Kapeller J., Schütz B. (2020). Die Vermessung Der Globalisierung, in: _Makronom -- Online Magazin für Wirtschaftspolitik_, January: [Link](https://makronom.de/oekonomische-offenheit-die-vermessung-der-globalisierung-37176).

## 2019

- **Gräbner C.**, Heimberger P., Kapeller J., Schütz B. (2019). Eine Strategie Gegen Die Ökonomische Polarisierung Europas, in: _Makronom -- Online Magazin für Wirtschaftspolitik_, September: [Link](https://makronom.de/eine-strategie-gegen-die-oekonomische-polarisierung-europas-32115).

- **Gräbner C.** (2019). Why Europe Is Drifting Apart and What to Do about It, in: _The Rebuilding Macroeconomics Blog_, April: [Link](https://www.rebuildingmacroeconomics.ac.uk/europe-drifting-apart/).

## 2018

- Heimberger P., **Gräbner C.**, Kapeller J., Schütz B. (2018). Eine Strategie Gegen Die Ökonomische Polarisierung Europas, in: _Makronom -- Online Magazin für Wirtschaftspolitik_, March: [Link](https://makronom.de/polarisierung-konvergenz-warum-europa-trotz-aufschwung-oekonomisch-weiter-auseinander-driftet-25782).

<!-- /nonacademicpubs -->